# Generated by Django 3.1 on 2020-08-27 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amsite', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='img',
            field=models.CharField(default='https://www.generationsforpeace.org/wp-content/uploads/2018/03/empty.jpg', max_length=100),
        ),
    ]
